export const ArtData = {
  becca: [
    {
      fileName: "Moonlight 1.png",
      artName: "Becca Lyria",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "Moonlight 3.png",
      artName: "A Forest Adventure",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "Moonlight 4.png",
      artName: "A Day at the Beach",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "Moonlight 5.png",
      artName: "Princess Becca",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "Moonlight 6.jpg",
      artName: "Sketch",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "Starfazers.png",
      artName: "Chilling at the Park",
      artist: "Starfazers",
      artistUrl: "https://instagram.com/starfazers",
    },
    {
      fileName: "Ashley.jpg",
      artName: "A Wink and a Kiss",
      artist: "Ashley",
      artistUrl: "https://www.instagram.com/tbg_art/",
    },
    {
      fileName: "shiroGEM.png",
      artName: "Ready to Fight",
      artist: "crys-chris",
      artistUrl: "https://crys-chris.carrd.co/",
    },
    {
      fileName: "Inspector Luke Warm.png",
      artName: "Vitriol",
      artist: "Inspector Luke Warm",
      artistUrl:
        "https://www.gaiaonline.com/profiles/inspector-luke-warm/20324544/",
    },
    {
      fileName: "Dyabolus.png",
      artName: "Another Day",
      artist: "Dyabolus",
      artistUrl: "https://www.gaiaonline.com/profiles/dyabolus/4366582/",
    },
    {
      fileName: "Euphoria-Cyrab.jpg",
      artName: "Dressed Up for Summer",
      artist: "Unknown",
      artistUrl: "https://www.beccalyria.com",
    },
    {
      fileName: "Princess Geekfayce.png",
      artName: "Shy Elegance",
      artist: "Princess Geekfayce",
      artistUrl:
        "https://www.gaiaonline.com/profiles/princess-geekfayce/5671848/",
    },
    {
      fileName: "RinHekka.png",
      artName: "Young Becca",
      artist: "EvilKingRin",
      artistUrl: "https://www.deviantart.com/evilkingrin",
    },
    {
      fileName: "Ruvik Victoriano.png",
      artName: "Sassy Queen",
      artist: "Ruvik Victoriano",
      artistUrl:
        "https://www.gaiaonline.com/profiles/ruvik-victoriano/38974251/",
    },
    {
      fileName: "TiffanyBlueSprinkles.png",
      artName: "The Royal Ball",
      artist: "Tiffany",
      artistUrl: "https://www.instagram.com/itiffanyblue/",
    },
    {
      fileName: "wispur.png",
      artName: "Feeling Flirty",
      artist: "Unknown",
      artistUrl: "https://www.beccalyria.com",
    },
    {
      fileName: "Xiyara.png",
      artName: "Playful",
      artist: "Unknown",
      artistUrl: "https://www.beccalyria.com",
    },
    {
      fileName: "claudoodles.png",
      artName: "Shining Beauty",
      artist: "claudoodles",
      artistUrl: "https://twitter.com/claudoodles_",
    },
    {
      fileName: "Lena_Smith11.jpg",
      artName: "A Night on the Town",
      artist: "Lena",
      artistUrl: "https://twitter.com/lena_smith11",
    },
    {
      fileName: "coffee.png",
      artName: "White Mocha With Extra Becca",
      artist: "HalleyWoofs",
      artistUrl: "https://halleywoofs.art",
    },
    {
      fileName: "kato_token.png",
      artName: "Token",
      artist: "Kato",
      artistUrl: "https://362studios.carrd.co/",
    },
    {
      fileName: "melty-wink.jpg",
      artName: "Wink",
      artist: "MeltyDraws",
      artistUrl: "https://twitter.com/MeltyDraws",
    },
  ],
  beccalia: [
    {
      fileName: "moonlight.png",
      artName: "Untitled",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "dance.png",
      artName: "Dance",
      artist: "Starfazers",
      artistUrl: "https://starfazers.art/",
    },
    {
      fileName: "banner.jpg",
      artName: "Banner",
      artist: "Lena",
      artistUrl: "https://twitter.com/lena_smith11",
    },
    {
      fileName: "a-night-out.jpg",
      artName: "A Night Out",
      artist: "Lena",
      artistUrl: "https://twitter.com/lena_smith11",
    },
    {
      fileName: "evening-snuggle.jpg",
      artName: "Evening Snuggle",
      artist: "Sherhan",
      artistUrl: "https://twitter.com/sherhan3666",
    },
    {
      fileName: "relaxation.png",
      artName: "Relaxation",
      artist: "claudoodles",
      artistUrl: "https://twitter.com/claudoodles_",
    },
    {
      fileName: "wedding-day.png",
      artName: "Wedding Day",
      artist: "Starfazers",
      artistUrl: "https://starfazers.art/",
    },
    {
      fileName: "beach.png",
      artName: "A Day at the Beach",
      artist: "Devonxy1",
      artistUrl: "https://twitter.com/Devonxy1",
    },
  ],
  rosalia: [
    {
      fileName: "moonlight1.jpg",
      artName: "And I Wake Up Falling",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "moonlight2.png",
      artName: "Cover",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "moonlight3.png",
      artName: "Dance of the Dove",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "moonlight4.png",
      artName: "Delicate Angel",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "moonlight5.png",
      artName: "Disbelief",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "moonlight6.jpg",
      artName: "Entangled Emotions",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "moonlight7.jpg",
      artName: "Follow Me",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "moonlight8.jpg",
      artName: "Oasis",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "moonlight9.jpg",
      artName: "Rosalia",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "moonlight10.jpg",
      artName: "Soar",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "moonlight11.jpg",
      artName: "Song of the Nightingale",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "moonlight12.png",
      artName: "The Beautiful Question",
      artist: "Moonlight",
      artistUrl: "https://www.instagram.com/moonlightkcreations/",
    },
    {
      fileName: "ashley.jpg",
      artName: "Warrior",
      artist: "Ashley Shaw",
      artistUrl: "https://www.instagram.com/tbg_art/",
    },
    {
      fileName: "our-playful-hero.jpg",
      artName: "Our Playful Hero",
      artist: "unknown",
      artistUrl: "https://www.rosalianightsong.com",
    },
    {
      fileName: "between-the-raindrops.jpg",
      artName: "Between the Raindrops",
      artist: "unknown",
      artistUrl: "https://www.rosalianightsong.com",
    },
    {
      fileName: "sunday-best.jpg",
      artName: "Sunday Best",
      artist: "unknown",
      artistUrl: "https://www.rosalianightsong.com",
    },
    {
      fileName: "will-of-the-heart.jpg",
      artName: "Will of the Heart",
      artist: "unknown",
      artistUrl: "https://www.rosalianightsong.com",
    },
    {
      fileName: "untitled.jpg",
      artName: "Divine Elegance",
      artist: "unknown",
      artistUrl: "https://www.rosalianightsong.com",
    },
    {
      fileName: "gateway-of-roses.jpg",
      artName: "Gateway of Roses",
      artist: "unknown",
      artistUrl: "https://www.rosalianightsong.com",
    },
    {
      fileName: "untitled2.jpg",
      artName: "Swift Justice",
      artist: "unknown",
      artistUrl: "https://www.rosalianightsong.com",
    },
    {
      fileName: "untitled3.jpg",
      artName: "The Sweetest Smile",
      artist: "unknown",
      artistUrl: "https://www.rosalianightsong.com",
    },
    {
      fileName: "lena_smith11.jpg",
      artName: "A Night on the Town",
      artist: "Lena",
      artistUrl: "https://www.twitter.com/lena_smith11/",
    },
  ],
};
